services:

  app:
    image: regtest-front-prod
    build:
      context: ./front #set the directory path 
      dockerfile: Dockerfile
    volumes:
      - ./front:/usr/src/app #set the directory path 
    container_name: regtest-front-prod

  server:
    image: regtest-back-prod
    build: 
      context: ./back #set the directory path 
      dockerfile: Dockerfile
    volumes:
      - ./back:/usr/src/app #set the directory path 
    container_name: regtest-back-prod

  nginx:
    image: nginx:1.25-alpine
    container_name: nginx-regtest
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
      - server